language: ruby
rvm:
  - '2.1.4'
services:
  - elasticsearch
before_install:
  - sudo apt-get install -qq phantomjs
before_script:
  - psql -c 'create database pf_engine_test;' -U postgres
notifications:
  email: false
